# Generated by Django 4.0.3 on 2023-02-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0003_remove_leaderboard_player_remove_module_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
        migrations.AlterField(
            model_name='module',
            name='page_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('orientation', models.IntegerField()),
                ('active', models.BooleanField()),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='well_of_maxwell.content')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_voltage', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='well_of_maxwell.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('orientation', models.IntegerField()),
                ('active', models.BooleanField()),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='well_of_maxwell.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='well_of_maxwell.module'),
        ),
    ]
