# Generated by Django 4.0.3 on 2023-02-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0005_remove_content_active_remove_text_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
        migrations.RemoveField(
            model_name='image',
            name='orientation',
        ),
        migrations.AddField(
            model_name='module',
            name='page_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
