# Generated by Django 4.0.3 on 2023-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0008_exercise_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.IntegerField(default=0),
        ),
    ]
