# Generated by Django 4.0.3 on 2023-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0009_module_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
