# Generated by Django 4.2 on 2023-04-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0010_module_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='exercise_block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='well_of_maxwell.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct',
            field=models.CharField(max_length=50),
        ),
    ]
