# Generated by Django 4.2 on 2023-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0012_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
