# Generated by Django 4.2 on 2023-05-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well_of_maxwell', '0015_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
